In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("C:/Users/HP/Downloads/kdramas/all_series.csv")
df1.head(1)

,tmdb_id,name,original_name,keywords,airing_date,poster_img_url,background_img_url,directors_ids,cast_ids,genres_ids,...,episode_run_time,synopsis,popularity,average_rating,rating_count,next_episode_to_air,next_episode_air_date,origin_country,networks_ids,production_companies_ids
0,136699,Glitch,글리치,"friendship, investigation, ufo, miniseries, su...",2022-10-07,https://image.tmdb.org/t/p/original/dspwDOosid...,https://image.tmdb.org/t/p/original/3O5voBAoeQ...,1293597,"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",...,54.0,A young woman joins forces with a UFO enthusia...,520.913,7.7,22.0,NaN,NaN,KR,213,133335

In [3]:
df1 = df1.drop(['original_name','airing_date','background_img_url','number_of_seasons','number_of_episodes','episode_run_time','popularity','average_rating','rating_count','next_episode_to_air','next_episode_air_date','origin_country','networks_ids','production_companies_ids'],axis='columns')
df1.head(1)

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,1293597,"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",A young woman joins forces with a UFO enthusia...

In [4]:
df1.isnull().sum()

tmdb_id              0
name                 0
keywords           549
poster_img_url     101
directors_ids     1350
cast_ids            30
genres_ids           0
synopsis            83
dtype: int64

In [5]:
df1 = df1.dropna()

In [6]:
df1.shape

(131, 8)

In [7]:
dir_name = pd.read_csv("C:/Users/HP/Downloads/kdramas/people.csv")
dir_name.head(1)

,tmdb_id,name,biography,place_of_birth,birthday,deathday,gender,known_for_department,popularity,profile_img_url
0,1257661,Lee El,"Kim Ji-hyun, better known by her stage name EL...","Seoul, South Korea",1982-08-26,NaN,1.0,Acting,10.688,https://image.tmdb.org/t/p/original/cXG6IcCaqt...

In [8]:
dir_name = dir_name.drop(['biography','place_of_birth','birthday','deathday','gender','known_for_department','popularity','profile_img_url'],axis='columns')
dir_name.head(2)

   tmdb_id         name
0  1257661       Lee El
1  2097078  Jeon Jin-gi

In [9]:
x=1257661
dir_name.loc[dir_name['tmdb_id']==x,"name"].item()

'Lee El'

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131 entries, 0 to 1374
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tmdb_id         131 non-null    int64
 1   name            131 non-null    object
 2   keywords        131 non-null    object
 3   poster_img_url  131 non-null    object
 4   directors_ids   131 non-null    object
 5   cast_ids        131 non-null    object
 6   genres_ids      131 non-null    object
 7   synopsis        131 non-null    object
dtypes: int64(1), object(7)
memory usage: 9.2+ KB

In [11]:
no = df1['directors_ids']
no

0       1293597
1       1182291
2       1294471
5       1724565
6        939147
         ...
1123     117498
1153    3527566
1323    1764050
1330    1902848
1374    3192063
Name: directors_ids, Length: 131, dtype: object

In [12]:
df1['directors_ids'] = df1['directors_ids'].apply(lambda x: list(x.split(",")))

In [13]:
df1.head(1)

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,[1293597],"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",A young woman joins forces with a UFO enthusia...

In [14]:
def change(num):
    list1=[]
    for i in num:
      list1.append(dir_name.loc[dir_name['tmdb_id']==int(i),"name"].item())
    return list1
#Lee El
#Jeon Jin-gi
list_demo = ['1257661','2097078']
change(list_demo)

['Lee El', 'Jeon Jin-gi']

In [15]:
x = df1['directors_ids'][0]
df1['directors_ids'] = df1.directors_ids.apply(change)

In [16]:
df1.head(3)

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,[Roh Deok],"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",A young woman joins forces with a UFO enthusia...
1,99966,All of Us Are Dead,"high school, bullying, based on comic, horror,...",https://image.tmdb.org/t/p/original/pTEFqAjLd5...,[JQ Lee],"2125084, 1493898, 2185341, 2074587, 2402531, 1...","10759, 18, 10765",A high school becomes ground zero for a zombie...
2,93405,Squid Game,"secret organization, challenge, survival, fict...",https://image.tmdb.org/t/p/original/dDlEmu3EZ0...,[Hwang Dong-hyuk],"73249, 1593672, 3194501, 1557181, 1048070, 191...","10759, 9648, 18",Hundreds of cash-strapped players accept a str...

In [17]:
df1['cast_ids'] = df1['cast_ids'].apply(lambda x: list(x.split(",")))

In [18]:
df1['cast_ids'][0]

['2067860',
 ' 1523043',
 ' 1418580',
 ' 2239782',
 ' 150697',
 ' 1747532',
 ' 181332',
 ' 1511024',
 ' 3138793',
 ' 1605872',
 ' 2120094',
 ' 2758995',
 ' 2878492',
 ' 1572347',
 ' 2003804',
 ' 939133',
 ' 2098630',
 ' 2840538',
 ' 2124185']

In [19]:
def change(num):
    list1=[]
    j=0
    for i in num:
        if(j<3):
            list1.append(dir_name.loc[dir_name['tmdb_id']==int(i),"name"].item())
            j +=1
    return list1
#Lee El
#Jeon Jin-gi
list_demo = [2067860, 1523043, 1418580, 2239782]
change(list_demo)

['Jeon Yeo-been', 'Nana', 'Lee Dong-hwi']

In [20]:
df1['cast_ids'] = df1.cast_ids.apply(change)

In [21]:
df1.genres_ids[0]

'18, 35, 9648, 10765'

In [22]:
gen_name = pd.read_csv("C:/Users/HP/Downloads/kdramas/genres.csv")
gen_name.head()

   tmdb_id                name
0       18               Drama
1       35              Comedy
2     9648             Mystery
3    10765    Sci-Fi & Fantasy
4    10759  Action & Adventure

In [23]:
def change(num):
    list1=[]
    for i in num:
        list1.append(gen_name.loc[gen_name['tmdb_id']==int(i),"name"].item())
    return list1
#Lee El
#Jeon Jin-gi
list_demo = [18, 35, 9648, 10765]
change(list_demo)

['Drama', 'Comedy', 'Mystery', 'Sci-Fi & Fantasy']

In [24]:
df1['genres_ids'] = df1['genres_ids'].apply(lambda x: list(x.split(",")))

In [83]:
df1.head()

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis,tags
0,136699,Glitch,"[friendship, investigation, ufo, miniseries, s...",https://image.tmdb.org/t/p/original/dspwDOosid...,[RohDeok],"[JeonYeo-been, Nana, LeeDong-hwi]","[Drama, Comedy, Mystery, Sci-Fi&Fantasy]","[A, young, woman, joins, forces, with, a, UFO,...","[A, young, woman, joins, forces, with, a, UFO,..."
1,99966,All of Us Are Dead,"[highschool, bullying, basedoncomic, horror, c...",https://image.tmdb.org/t/p/original/pTEFqAjLd5...,[JQLee],"[ParkJi-hu, YoonChan-young, ChoYi-hyun]","[Action&Adventure, Drama, Sci-Fi&Fantasy]","[A, high, school, becomes, ground, zero, for, ...","[A, high, school, becomes, ground, zero, for, ..."
2,93405,Squid Game,"[secretorganization, challenge, survival, fict...",https://image.tmdb.org/t/p/original/dDlEmu3EZ0...,[HwangDong-hyuk],"[LeeJung-jae, ParkHae-soo, JungHo-yeon]","[Action&Adventure, Mystery, Drama]","[Hundreds, of, cash-strapped, players, accept,...","[Hundreds, of, cash-strapped, players, accept,..."
5,67915,Goblin,"[romance, superpower, pastlife, immortal]",https://image.tmdb.org/t/p/original/c2gon6zbqz...,[LeeEung-bok],"[GongYoo, KimGo-eun, LeeDong-wook]","[Drama, Sci-Fi&Fantasy]","[In, his, quest, for, a, bride, to, break, his...","[In, his, quest, for, a, bride, to, break, his..."
6,106651,Hellbound,"[hell, cult, basedoncartoon, supernaturalcreat...",https://image.tmdb.org/t/p/original/5NYdSAnDVI...,[YeonSang-ho],"[YooAh-in, KimHyun-joo, ParkJeong-min]","[Drama, Crime, Sci-Fi&Fantasy]","[Unearthly, beings, deliver, bloody, condemnat...","[Unearthly, beings, deliver, bloody, condemnat..."

In [26]:
df1['genres_ids'] = df1.genres_ids.apply(change)

In [86]:
df1.head()

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis,tags
0,136699,Glitch,"[friendship, investigation, ufo, miniseries, s...",https://image.tmdb.org/t/p/original/dspwDOosid...,[RohDeok],"[JeonYeo-been, Nana, LeeDong-hwi]","[Drama, Comedy, Mystery, Sci-Fi&Fantasy]","[A, young, woman, joins, forces, with, a, UFO,...","[A, young, woman, joins, forces, with, a, UFO,..."
1,99966,All of Us Are Dead,"[highschool, bullying, basedoncomic, horror, c...",https://image.tmdb.org/t/p/original/pTEFqAjLd5...,[JQLee],"[ParkJi-hu, YoonChan-young, ChoYi-hyun]","[Action&Adventure, Drama, Sci-Fi&Fantasy]","[A, high, school, becomes, ground, zero, for, ...","[A, high, school, becomes, ground, zero, for, ..."
2,93405,Squid Game,"[secretorganization, challenge, survival, fict...",https://image.tmdb.org/t/p/original/dDlEmu3EZ0...,[HwangDong-hyuk],"[LeeJung-jae, ParkHae-soo, JungHo-yeon]","[Action&Adventure, Mystery, Drama]","[Hundreds, of, cash-strapped, players, accept,...","[Hundreds, of, cash-strapped, players, accept,..."
5,67915,Goblin,"[romance, superpower, pastlife, immortal]",https://image.tmdb.org/t/p/original/c2gon6zbqz...,[LeeEung-bok],"[GongYoo, KimGo-eun, LeeDong-wook]","[Drama, Sci-Fi&Fantasy]","[In, his, quest, for, a, bride, to, break, his...","[In, his, quest, for, a, bride, to, break, his..."
6,106651,Hellbound,"[hell, cult, basedoncartoon, supernaturalcreat...",https://image.tmdb.org/t/p/original/5NYdSAnDVI...,[YeonSang-ho],"[YooAh-in, KimHyun-joo, ParkJeong-min]","[Drama, Crime, Sci-Fi&Fantasy]","[Unearthly, beings, deliver, bloody, condemnat...","[Unearthly, beings, deliver, bloody, condemnat..."

In [28]:
df1['synopsis'][0]

'A young woman joins forces with a UFO enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy.'

In [29]:
df1['synopsis'] = df1['synopsis'].apply(lambda x : list(x.split(" ")))

In [30]:
df1['keywords'] = df1['keywords'].apply(lambda x : list(x.split(",")))

In [31]:
df1['keywords'] = df1['keywords'].apply(lambda x : [i.replace(" ","") for i in x])

In [32]:
df1['cast_ids'] = df1['cast_ids'].apply(lambda x : [i.replace(" ","") for i in x])
df1['directors_ids'] = df1['directors_ids'].apply(lambda x : [i.replace(" ","") for i in x])
df1['genres_ids'] = df1['genres_ids'].apply(lambda x : [i.replace(" ","") for i in x])

In [33]:
df1['tags'] = df1['synopsis'] + df1['cast_ids'] + df1['directors_ids'] + df1['genres_ids'] + df1['keywords']

In [34]:
df1['tags'].head(1)

0    [A, young, woman, joins, forces, with, a, UFO,...
Name: tags, dtype: object

In [35]:
new_df = df1[['tmdb_id','name','tags']]

In [36]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\HP\AppData\Local\Temp/ipykernel_8908/3530946481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [37]:
new_df['tags'][0]

'A young woman joins forces with a UFO enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy. JeonYeo-been Nana LeeDong-hwi RohDeok Drama Comedy Mystery Sci-Fi&Fantasy friendship investigation ufo miniseries suspense'

In [38]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

C:\Users\HP\AppData\Local\Temp/ipykernel_8908/3679624391.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

In [39]:
new_df.head()

,tmdb_id,name,tags
0,136699,Glitch,a young woman joins forces with a ufo enthusia...
1,99966,All of Us Are Dead,a high school becomes ground zero for a zombie...
2,93405,Squid Game,hundreds of cash-strapped players accept a str...
5,67915,Goblin,in his quest for a bride to break his immortal...
6,106651,Hellbound,"unearthly beings deliver bloody condemnations,..."

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [56]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [57]:
cv.get_feature_names()

['000',
 '05',
 '10',
 '100',
 '13',
 '15',
 '18',
 '1885',
 '19',
 '1900s',
 '1930',
 '1970',
 '1975',
 '1980s',
 '1987',
 '1990',
 '1997',
 '19th',
 '20',
 '2000',
 '2001',
 '2002',
 '2005',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2070',
 '21',
 '24',
 '25',
 '28',
 '29',
 '30',
 '30s',
 '31',
 '33',
 '35',
 '350',
 '40',
 '41',
 '49',
 '55',
 '5th',
 '60th',
 '70',
 '939',
 '999',
 'abandon',
 'abduct',
 'abid',
 'ability',
 'abl',
 'absolut',
 'abuseofpow',
 'academ',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accomplish',
 'accus',
 'achiev',
 'act',
 'action',
 'actor',
 'actress',
 'actual',
 'adapt',
 'addict',
 'adequ',
 'adopt',
 'adulthood',
 'adventur',
 'advers',
 'ae',
 'afar',
 'affect',
 'affili',
 'aft',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agechang',
 'agenc',
 'agent',
 'ago',
 'agre',
 'agreement',
 'ah',
 'ahn',
 'ahnbo',
 'ahngil',
 'ahnhyo',
 'ahnjae',
 'ahnnae',
 'ahnsang',
 'air',
 'airplan',
 'airplaneaccid',
 'ajumma',
 'aka',
 'alley',
 'alway',
 'ambassador',
 'ambit',
 'america',
 'amidst',
 'amnesia',
 'ancient',
 'ancientkorea',
 'angel',
 'ani',
 'anniversari',
 'announc',
 'anoth',
 'antholog',
 'antisoci',
 'antisocialpersonalitydisord',
 'anyth',
 'apart',
 'apocalyps',
 'apocalypticfutur',
 'app',
 'appeal',
 'appear',
 'appearance',
 'applianc',
 'appoint',
 'april',
 'archaeologist',
 'area',
 'arrog',
 'art',
 'arth',
 'arthdal',
 'artificialintellig',
 'artist',
 'arts',
 'asahi',
 'ashley',
 'asian',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assassination',
 'assembly',
 'assist',
 'assum',
 'athelet',
 'attempt',
 'attend',
 'attorney',
 'attract',
 'attraction',
 'audienc',
 'audiences',
 'author',
 'autism',
 'autist',
 'autobiograph',
 'averag',
 'avers',
 'await',
 'award',
 'awards',
 'away',
 'ba',
 'babi',
 'backdrop',
 'background',
 'bad',
 'bae',
 'baedoona',
 'baehae',
 'baehyeon',
 'baein',
 'baek',
 'baeksang',
 'baeksoo',
 'baeksung',
 'baesuzi',
 'baeyong',
 'baggag',
 'balanc',
 'band',
 'banker',
 'bankruptci',
 'bar',
 'bargain',
 'base',
 'basebal',
 'baseballplay',
 'basedoncartoon',
 'basedoncom',
 'basedonmovi',
 'basedonnovelorbook',
 'basedonshortfilm',
 'basedontruestori',
 'basedonwebcomicorwebtoon',
 'battl',
 'battlefield',
 'bawdi',
 'beach',
 'bead',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'befor',
 'begin',
 'behindthescen',
 'bekhyun',
 'belief',
 'believ',
 'belov',
 'benefit',
 'beom',
 'best',
 'bestsel',
 'bestsellingauthor',
 'betray',
 'better',
 'big',
 'biggest',
 'billion',
 'bin',
 'biographi',
 'birth',
 'bit',
 'bitter',
 'bizarr',
 'bl',
 'black',
 'blind',
 'blinddat',
 'bliss',
 'blood',
 'bloodi',
 'blunt',
 'bodi',
 'body',
 'bodyguard',
 'bok',
 'bomb',
 'bona',
 'bond',
 'bong',
 'boost',
 'born',
 'borrow',
 'boss',
 'bossam',
 'bountyhunt',
 'bowel',
 'boxer',
 'boy',
 'boyband',
 'boyfriend',
 'boys',
 'brain',
 'brainsurgeri',
 'brawn',
 'break',
 'bride',
 'bright',
 'brighter',
 'brilliant',
 'brink',
 'broadcast',
 'broke',
 'broken',
 'brokenpromis',
 'bromanc',
 'brother',
 'brotherhood',
 'brothersisterrelationship',
 'buam',
 'buddha',
 'build',
 'built',
 'bulli',
 'bulling',
 'burn',
 'busan',
 'business',
 'businessman',
 'butcher',
 'byeonwoo',
 'byul',
 'calcul',
 'came',
 'camera',
 'campus',
 'campuslif',
 'campusrom',
 'cancer',
 'captur',
 'car',
 'caraccid',
 'card',
 'care',
 'career',
 'caregiv',
 'carrefour',
 'carri',
 'case',
 'cases',
 'cash',
 'casino',
 'cassano',
 'castl',
 'catastroph',
 'caught',
 'caus',
 'center',
 'centuries',
 'ceo',
 'cha',
 'chae',
 'chaebol',
 'chaejong',
 'chaejung',
 'chain',
 'chairman',
 'chajaedol',
 'challeng',
 'chan',
 'chanc',
 'chang',
 'changryul',
 'chao',
 'chaotic',
 'charact',
 'characterdevelop',
 'charae',
 'charisma',
 'charismaticfemalelead',
 'charm',
 'chart',
 'chase',
 'chast',
 'cheat',
 'chef',
 'cheol',
 'cheom',
 'cheon',
 'chief',
 'child',
 'childabus',
 'childhood',
 'childhoodfriend',
 'childhoodtrauma',
 'children',
 'china',
 'cho',
 'choechanyi',
 'chohyuk',
 'choi',
 'choic',
 'choihang',
 'choijung',
 'choimin',
 'choimoon',
 'choisoo',
 'choiwoo',
 'choiyeo',
 'choiyoung',
 'chojae',
 'chojung',
 'chomin',
 'chonam',
 'chooja',
 'choos',
 'chooyoung',
 'chorong',
 'chosen',
 'choseong',
 'choyi',
 'chu',
 'chul',
 'chun',
 'chung',
 'chunwoo',
 'cinderella',
 'cinematography',
 'circus',
 'citi',
 'city',
 'civil',
 'clad',
 'claim',
 'class',
 'classifi',
 'classmat',
 'cliff',
 'close',
 'closer',
 'clothing',
 'clown',
 'club',
 'clumsi',
 'coexist',
 'cohabit',
 'cold',
 'collaboration',
 'collaps',
 'collapse',
 'colleagu',
 'collect',
 'colleg',
 'college',
 'collegelif',
 'coloni',
 'color',
 'coma',
 'come',
 'comeback',
 'comedi',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'commemor',
 'commiss',
 'commit',
 'common',
 'commun',
 'communication',
 'compani',
 'company',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'compromis',
 'comrades',
 'concern',
 'condemnations',
 'condition',
 'conflict',
 'confront',
 'conglomer',
 'congress',
 'connect',
 'connected',
 'conscious',
 'consecut',
 'consiglier',
 'conspiraci',
 'conspiracy',
 'conspirators',
 'constantli',
 'consult',
 'continu',
 'control',
 'controversi',
 'conveni',
 'convict',
 'cook',
 'cop',
 'core',
 'corner',
 'corp',
 'corpor',
 'corrupt',
 'cosmet',
 'cost',
 'costs',
 'couldn',
 'council',
 'countri',
 'countrysid',
 'countryside',
 'coup',
 'coupl',
 'court',
 'courtcas',
 'courtroom',
 'cover',
 'crash',
 'creat',
 'creator',
 'crew',
 'cri',
 'crime',
 'crimin',
 'critic',
 'cross',
 'crossdress',
 'cruelti',
 'cult',
 'culture',
 'curs',
 'curse',
 'custom',
 'customari',
 'cut',
 'cutthroat',
 'cyberbulli',
 'cynic',
 'da',
 'dal',
 'dam',
 'danger',
 'dark',
 'darkfairytal',
 'date',
 'datingapp',
 'daughter',
 'dawoon',
 'day',
 'days',
 'dead',
 'deal',
 'death',
 'deathmatch',
 'deathofabroth',
 'debut',
 'deceas',
 'decemb',
 'decept',
 'decid',
 'decommiss',
 'dedic',
 'deepli',
 'defam',
 'defin',
 'degener',
 'delic',
 'deliv',
 'demand',
 'democrat',
 'deok',
 'depict',
 'depress',
 'dermatologist',
 'design',
 'desir',
 'desire',
 'desires',
 'desper',
 'destroy',
 'detect',
 'detective',
 'determin',
 'develop',
 'deviat',
 'did',
 'die',
 'died',
 'differ',
 'different',
 'difficult',
 'difficulti',
 'digest',
 'dilig',
 'dinner',
 'direction',
 'director',
 'directors',
 'dirti',
 'disappear',
 'disapprovingpar',
 'disast',
 'discharg',
 'disciple',
 'disconnect',
 'discov',
 'disease',
 'disguis',
 'dismissals',
 'disord',
 'display',
 'dissoci',
 'dissociativeidentitydisord',
 'district',
 'divin',
 'divorc',
 'divorcedman',
 'dj',
 'doctor',
 'doe',
 'doesn',
 'dogs',
 'dohkyung',
 'dong',
 'dongha',
 'donguibogam',
 'doo',
 'dormitori',
 'doubleident',
 'doubt',
 'downplay',
 'drag',
 'drama',
 'dramat',
 'draw',
 'drawn',
 'dream',
 'dreams',
 'driven',
 'drug',
 'drugdeal',
 'druglord',
 'dumpi',
 'dure',
 'dwi',
 'dying',
 'dynasti',
 'dynasty',
 'earli',
 'earth',
 'earthquak',
 'easi',
 'eat',
 'eating',
 'eccentr',
 'eccentricmalelead',
 'eclect',
 'economi',
 'economy',
 'educ',
 'education',
 'effort',
 'ehwa',
 'electronics',
 'elev',
 'elit',
 'eloqu',
 'els',
 'emancip',
 'emmi',
 'emot',
 'emotion',
 'emotionalbreakdown',
 'employ',
 'employe',
 'employee',
 'employeerelationship',
 'employees',
 'employer',
 'empress',
 'encag',
 'end',
 'enemi',
 'energi',
 'engag',
 'engineer',
 'enigmat',
 'enjoy',
 'ensnar',
 'ensu',
 'ensur',
 'entangl',
 'enter',
 'entertain',
 'entertainmentindustri',
 'enthusiast',
 'entranceexamin',
 'entrepreneur',
 'envi',
 'envis',
 'eom',
 'episod',
 'episodes',
 'epitom',
 'era',
 'error',
 'escap',
 'establish',
 'eulji',
 'eum',
 'eun',
 'eunji',
 'event',
 'events',
 'eventu',
 'everi',
 'everyday',
 'everyon',
 'everyth',
 'exactli',
 'examination',
 'excel',
 'exchanged',
 'exhaust',
 'exist',
 'exorc',
 'exorcist',
 'expand',
 'expans',
 'expatri',
 'expens',
 'experi',
 'experienc',
 'explor',
 'extraordinari',
 'extrem',
 'eye',
 'face',
 'facil',
 'fact',
 'faction',
 'factions',
 'fail',
 'fairi',
 'faith',
 'fakeident',
 'fall',
 'fallen',
 'fals',
 'fame',
 'famili',
 'family',
 'familydrama',
 'familyrelationship',
 'fanci',
 'fantasi',
 'fantasyworld',
 'far',
 'fashion',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'fault',
 'featur',
 'februari',
 'fee',
 'feel',
 'fell',
 'fellow',
 'femal',
 'femalecenteredplot',
 'femalefriendship',
 'femaleprotagonist',
 'femalewrit',
 'fenc',
 'fencer',
 'festiv',
 'festival',
 'fi',
 'fianc',
 'fiancé',
 'fiancée',
 'fiction',
 'fictionalgameshow',
 'field',
 'fifth',
 'fight',
 'fighter',
 'figur',
 'figures',
 'film',
 'final',
 'financi',
 'financialcrisi',
 'fine',
 'firm',
 'firstlov',
 'fish',
 'flashback',
 'fled',
 'flirtati',
 'flower',
 'focus',
 'folk',
 'follow',
 'food',
 'footstep',
 'forc',
 'forens',
 'forese',
 'forest',
 'form',
 'formerprison',
 'forth',
 'forti',
 'fought',
 'fox',
 'france',
 'fraud',
 'free',
 'freedom',
 'friend',
 'friendli',
 'friends',
 'friendship',
 'friendstolov',
 'frighten',
 'frosti',
 'frozen',
 'fulfil',
 'funeral',
 'fusion',
 'futur',
 'future',
 'gain',
 'gam',
 'gambles',
 'game',
 'games',
 'gang',
 'gangnam',
 'gangnamscand',
 'gangs',
 'gangster',
 'gather',
 'gau',
 'gave',
 'gayrom',
 'gener',
 'general',
 'genuin',
 'geon',
 'germany',
 'geun',
 'ghost',
 'ghosthunt',
 'gi',
 'giant',
 'gift',
 'girl',
 'girlfriend',
 'giveaway',
 'given',
 'glamor',
 'glorif',
 'goah',
 'gods',
 'goe',
 'goes',
 'goguryeo',
 'gohdoo',
 'gokyung',
 'gold',
 'golden',
 'gone',
 'gonghyo',
 'gongseung',
 'gongyoo',
 'goo',
 'good',
 'gook',
 'gore',
 'goryeodynasti',
 'gotop',
 'govern',
 'governmentoffici',
 'gowoo',
 'grade',
 'gradual',
 'graduat',
 'grand',
 'grandchild',
 'great',
 'greed',
 'greenhous',
 'grew',
 'grief',
 'grim',
 'grima',
 'grimreap',
 'gritti',
 'grittyfantasi',
 'ground',
 'group',
 'grow',
 'grown',
 'gu',
 'guard',
 'guardian',
 'guest',
 'guesthous',
 'guid',
 'guidance',
 'guild',
 'guilt',
 'guk',
 'gum',
 'gumiho',
 'gun',
 'gung',
 'guy',
 'gwangha',
 'gyeo',
 'ha',
 'habyung',
 'hae',
 'hahee',
 'hair',
 'haji',
 'hajun',
 'hajung',
 'half',
 'ham',
 'han',
 'hand',
 'handa',
 'handsom',
 'handsome',
 'hangi',
 'hanhe',
 'hanhye',
 'hani',
 'hanji',
 'hanseo',
 'hanso',
 'hansuk',
 'hanyeri',
 'happen',
 'happiness',
 'hard',
 'hardship',
 'hardwork',
 'head',
 'headquart',
 'heal',
 'heart',
 'heartwarm',
 'heaven',
 'heavenlyfantasi',
 'heavi',
 'heavili',
 'hee',
 'heekim',
 'heir',
 'hell',
 'help',
 'heo',
 'heon',
 'hero',
 'heuksa',
 'heung',
 'hi',
 'hiccup',
 'hidden',
 'hiddenident',
 'hide',
 'high',
 'highfantasi',
 'highlight',
 'highschool',
 'highschoolsport',
 'hilari',
 'hire',
 'histor',
 'historical',
 'historicaldrama',
 'historicalfict',
 'history',
 'hit',
 'ho',
 'hold',
 'holland',
 'hologram',
 'home',
 'hometown',
 'honest',
 'honesty',
 'hong',
 'hongchang',
 'hongji',
 'hongjong',
 'hongseok',
 'honor',
 'hoon',
 'hope',
 'horror',
 'hospit',
 'hospital',
 'hotel',
 'hoteli',
 'hotelier',
 'hour',
 'hous',
 'house',
 'housem',
 'housemates',
 'housew',
 'housewif',
 'houston',
 'hu',
 'huge',
 'human',
 'humanlik',
 'humor',
 'hun',
 'hundr',
 'hunter',
 'hurjin',
 'husband',
 'hwa',
 ...]

In [47]:
import nltk

In [49]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [50]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [51]:
new_df['tags'][0]

'a young woman joins forces with a ufo enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy. jeonyeo-been nana leedong-hwi rohdeok drama comedy mystery sci-fi&fantasy friendship investigation ufo miniseries suspense'

In [52]:
stem('a young woman joins forces with a ufo enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy. jeonyeo-been nana leedong-hwi rohdeok drama comedy mystery sci-fi&fantasy friendship investigation ufo miniseries suspense')

'a young woman join forc with a ufo enthusiast to investig her boyfriend’ sudden disappear and stumbl into a wild conspiracy. jeonyeo-been nana leedong-hwi rohdeok drama comedi mysteri sci-fi&fantasi friendship investig ufo miniseri suspens'

In [54]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp/ipykernel_8908/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
similarity = cosine_similarity(vectors)

In [64]:
similarity

array([[1.        , 0.13430383, 0.05647825, ..., 0.05504819, 0.1266601 ,
        0.01785999],
       [0.13430383, 1.        , 0.12515654, ..., 0.048795  , 0.03742406,
        0.01583119],
       [0.05647825, 0.12515654, 1.        , ..., 0.05129892, 0.03934447,
        0.03328713],
       ...,
       [0.05504819, 0.048795  , 0.05129892, ..., 1.        , 0.153393  ,
        0.09733285],
       [0.1266601 , 0.03742406, 0.03934447, ..., 0.153393  , 1.        ,
        0.02488363],
       [0.01785999, 0.01583119, 0.03328713, ..., 0.09733285, 0.02488363,
        1.        ]])

In [67]:
new_df[new_df['name']=='Glitch'].index[0]

0

In [81]:
def recommend(kdrama):
    drama_index = new_df[new_df['name']==kdrama].index[0]
    distances = similarity[drama_index]
    drama_list = sorted(list(enumerate(distances)),reverse = True, key = lambda x : x[1])[1:6]
    
    for i in drama_list:
        print(new_df.iloc[i[0]]["name"])

In [90]:
recommend('Goblin')

Woori The Virgin
Somebody
18 Again
Friend, Our Legend
Because This Is My First Life