In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("C:/Users/HP/Downloads/kdramas/all_series.csv")
df1.head(1)

,tmdb_id,name,original_name,keywords,airing_date,poster_img_url,background_img_url,directors_ids,cast_ids,genres_ids,...,episode_run_time,synopsis,popularity,average_rating,rating_count,next_episode_to_air,next_episode_air_date,origin_country,networks_ids,production_companies_ids
0,136699,Glitch,글리치,"friendship, investigation, ufo, miniseries, su...",2022-10-07,https://image.tmdb.org/t/p/original/dspwDOosid...,https://image.tmdb.org/t/p/original/3O5voBAoeQ...,1293597,"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",...,54.0,A young woman joins forces with a UFO enthusia...,520.913,7.7,22.0,NaN,NaN,KR,213,133335

In [3]:
df1 = df1.drop(['original_name','airing_date','background_img_url','number_of_seasons','number_of_episodes','episode_run_time','popularity','average_rating','rating_count','next_episode_to_air','next_episode_air_date','origin_country','networks_ids','production_companies_ids'],axis='columns')
df1.head(1)

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,1293597,"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",A young woman joins forces with a UFO enthusia...

In [6]:
df1.isnull().sum()

tmdb_id           0
name              0
keywords          0
poster_img_url    0
directors_ids     0
cast_ids          0
genres_ids        0
synopsis          0
dtype: int64

In [5]:
df1 = df1.dropna()

In [7]:
df1.shape

(131, 8)

In [8]:
dir_name = pd.read_csv("C:/Users/HP/Downloads/kdramas/people.csv")
dir_name.head(1)

,tmdb_id,name,biography,place_of_birth,birthday,deathday,gender,known_for_department,popularity,profile_img_url
0,1257661,Lee El,"Kim Ji-hyun, better known by her stage name EL...","Seoul, South Korea",1982-08-26,NaN,1.0,Acting,10.688,https://image.tmdb.org/t/p/original/cXG6IcCaqt...

In [9]:
dir_name = dir_name.drop(['biography','place_of_birth','birthday','deathday','gender','known_for_department','popularity','profile_img_url'],axis='columns')
dir_name.head(2)

   tmdb_id         name
0  1257661       Lee El
1  2097078  Jeon Jin-gi

In [10]:
x=1257661
dir_name.loc[dir_name['tmdb_id']==x,"name"].item()

'Lee El'

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131 entries, 0 to 1374
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tmdb_id         131 non-null    int64
 1   name            131 non-null    object
 2   keywords        131 non-null    object
 3   poster_img_url  131 non-null    object
 4   directors_ids   131 non-null    object
 5   cast_ids        131 non-null    object
 6   genres_ids      131 non-null    object
 7   synopsis        131 non-null    object
dtypes: int64(1), object(7)
memory usage: 9.2+ KB

In [12]:
no = df1['directors_ids']
no

0       1293597
1       1182291
2       1294471
5       1724565
6        939147
         ...
1123     117498
1153    3527566
1323    1764050
1330    1902848
1374    3192063
Name: directors_ids, Length: 131, dtype: object

In [13]:
df1['directors_ids'] = df1['directors_ids'].apply(lambda x: list(x.split(",")))

In [14]:
df1.head(1)

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,[1293597],"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",A young woman joins forces with a UFO enthusia...

In [15]:
def change(num):
    list1=[]
    for i in num:
      list1.append(dir_name.loc[dir_name['tmdb_id']==int(i),"name"].item())
    return list1
#Lee El
#Jeon Jin-gi
list_demo = ['1257661','2097078']
change(list_demo)

['Lee El', 'Jeon Jin-gi']

In [16]:
x = df1['directors_ids'][0]
df1['directors_ids'] = df1.directors_ids.apply(change)

In [17]:
df1.head(3)

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,[Roh Deok],"2067860, 1523043, 1418580, 2239782, 150697, 17...","18, 35, 9648, 10765",A young woman joins forces with a UFO enthusia...
1,99966,All of Us Are Dead,"high school, bullying, based on comic, horror,...",https://image.tmdb.org/t/p/original/pTEFqAjLd5...,[JQ Lee],"2125084, 1493898, 2185341, 2074587, 2402531, 1...","10759, 18, 10765",A high school becomes ground zero for a zombie...
2,93405,Squid Game,"secret organization, challenge, survival, fict...",https://image.tmdb.org/t/p/original/dDlEmu3EZ0...,[Hwang Dong-hyuk],"73249, 1593672, 3194501, 1557181, 1048070, 191...","10759, 9648, 18",Hundreds of cash-strapped players accept a str...

In [18]:
df1['cast_ids'] = df1['cast_ids'].apply(lambda x: list(x.split(",")))

In [19]:
df1['cast_ids'][0]

['2067860',
 ' 1523043',
 ' 1418580',
 ' 2239782',
 ' 150697',
 ' 1747532',
 ' 181332',
 ' 1511024',
 ' 3138793',
 ' 1605872',
 ' 2120094',
 ' 2758995',
 ' 2878492',
 ' 1572347',
 ' 2003804',
 ' 939133',
 ' 2098630',
 ' 2840538',
 ' 2124185']

In [20]:
def change(num):
    list1=[]
    j=0
    for i in num:
        if(j<3):
            list1.append(dir_name.loc[dir_name['tmdb_id']==int(i),"name"].item())
            j +=1
    return list1
#Lee El
#Jeon Jin-gi
list_demo = [2067860, 1523043, 1418580, 2239782]
change(list_demo)

['Jeon Yeo-been', 'Nana', 'Lee Dong-hwi']

In [21]:
df1['cast_ids'] = df1.cast_ids.apply(change)

In [22]:
df1.genres_ids[0]

'18, 35, 9648, 10765'

In [23]:
gen_name = pd.read_csv("C:/Users/HP/Downloads/kdramas/genres.csv")
gen_name.head()

   tmdb_id                name
0       18               Drama
1       35              Comedy
2     9648             Mystery
3    10765    Sci-Fi & Fantasy
4    10759  Action & Adventure

In [24]:
def change(num):
    list1=[]
    for i in num:
        list1.append(gen_name.loc[gen_name['tmdb_id']==int(i),"name"].item())
    return list1
#Lee El
#Jeon Jin-gi
list_demo = [18, 35, 9648, 10765]
change(list_demo)

['Drama', 'Comedy', 'Mystery', 'Sci-Fi & Fantasy']

In [25]:
df1['genres_ids'] = df1['genres_ids'].apply(lambda x: list(x.split(",")))

In [26]:
df1.head()

,tmdb_id,name,keywords,poster_img_url,directors_ids,cast_ids,genres_ids,synopsis
0,136699,Glitch,"friendship, investigation, ufo, miniseries, su...",https://image.tmdb.org/t/p/original/dspwDOosid...,[Roh Deok],"[Jeon Yeo-been, Nana, Lee Dong-hwi]","[18, 35, 9648, 10765]",A young woman joins forces with a UFO enthusia...
1,99966,All of Us Are Dead,"high school, bullying, based on comic, horror,...",https://image.tmdb.org/t/p/original/pTEFqAjLd5...,[JQ Lee],"[Park Ji-hu, Yoon Chan-young, Cho Yi-hyun]","[10759, 18, 10765]",A high school becomes ground zero for a zombie...
2,93405,Squid Game,"secret organization, challenge, survival, fict...",https://image.tmdb.org/t/p/original/dDlEmu3EZ0...,[Hwang Dong-hyuk],"[Lee Jung-jae, Park Hae-soo, Jung Ho-yeon]","[10759, 9648, 18]",Hundreds of cash-strapped players accept a str...
5,67915,Goblin,"romance, super power, past life, immortal",https://image.tmdb.org/t/p/original/c2gon6zbqz...,[Lee Eung-bok],"[Gong Yoo, Kim Go-eun, Lee Dong-wook]","[18, 10765]",In his quest for a bride to break his immortal...
6,106651,Hellbound,"hell, cult, based on cartoon, supernatural cre...",https://image.tmdb.org/t/p/original/5NYdSAnDVI...,[Yeon Sang-ho],"[Yoo Ah-in, Kim Hyun-joo, Park Jeong-min]","[18, 80, 10765]","Unearthly beings deliver bloody condemnations,..."

In [27]:
df1['genres_ids'] = df1.genres_ids.apply(change)

In [78]:
df1.poster_img_url[0]

'https://image.tmdb.org/t/p/original/dspwDOosidQT85oPDDHMM9zmaLw.jpg'

In [29]:
df1['synopsis'][0]

'A young woman joins forces with a UFO enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy.'

In [30]:
df1['synopsis'] = df1['synopsis'].apply(lambda x : list(x.split(" ")))

In [31]:
df1['keywords'] = df1['keywords'].apply(lambda x : list(x.split(",")))

In [32]:
df1['keywords'] = df1['keywords'].apply(lambda x : [i.replace(" ","") for i in x])

In [33]:
df1['cast_ids'] = df1['cast_ids'].apply(lambda x : [i.replace(" ","") for i in x])
df1['directors_ids'] = df1['directors_ids'].apply(lambda x : [i.replace(" ","") for i in x])
df1['genres_ids'] = df1['genres_ids'].apply(lambda x : [i.replace(" ","") for i in x])

In [34]:
df1['tags'] = df1['synopsis'] + df1['cast_ids'] + df1['directors_ids'] + df1['genres_ids'] + df1['keywords']

In [35]:
df1['tags'].head(1)

0    [A, young, woman, joins, forces, with, a, UFO,...
Name: tags, dtype: object

In [36]:
new_df = df1[['tmdb_id','name','tags']]

In [138]:
df1.shape

(131, 9)

In [37]:
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\HP\AppData\Local\Temp/ipykernel_9312/3530946481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [38]:
new_df['tags'][0]

'A young woman joins forces with a UFO enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy. JeonYeo-been Nana LeeDong-hwi RohDeok Drama Comedy Mystery Sci-Fi&Fantasy friendship investigation ufo miniseries suspense'

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

C:\Users\HP\AppData\Local\Temp/ipykernel_9312/3679624391.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

In [157]:
new_df.name[0:10]

0                         Glitch
1             All of Us Are Dead
2                     Squid Game
5                         Goblin
6                      Hellbound
7              Business Proposal
8     Extraordinary Attorney Woo
14                  Little Women
20                       My Name
21                The Silent Sea
Name: name, dtype: object

In [158]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [51]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [52]:
cv.get_feature_names()

['000',
 '05',
 '10',
 '100',
 '13',
 '15',
 '18',
 '1885',
 '19',
 '1900s',
 '1930',
 '1970',
 '1975',
 '1980s',
 '1987',
 '1990',
 '1997',
 '19th',
 '20',
 '2000',
 '2001',
 '2002',
 '2005',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2070',
 '21',
 '24',
 '25',
 '28',
 '29',
 '30',
 '30s',
 '31',
 '33',
 '35',
 '350',
 '40',
 '41',
 '49',
 '55',
 '5th',
 '60th',
 '70',
 '939',
 '999',
 'abandon',
 'abduct',
 'abid',
 'ability',
 'abl',
 'absolut',
 'abuseofpow',
 'academ',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accomplish',
 'accus',
 'achiev',
 'act',
 'action',
 'actor',
 'actress',
 'actual',
 'adapt',
 'addict',
 'adequ',
 'adopt',
 'adulthood',
 'adventur',
 'advers',
 'ae',
 'afar',
 'affect',
 'affili',
 'aft',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agechang',
 'agenc',
 'agent',
 'ago',
 'agre',
 'agreement',
 'ah',
 'ahn',
 'ahnbo',
 'ahngil',
 'ahnhyo',
 'ahnjae',
 'ahnnae',
 'ahnsang',
 'air',
 'airplan',
 'airplaneaccid',
 'ajumma',
 'aka',
 'alley',
 'alway',
 'ambassador',
 'ambit',
 'america',
 'amidst',
 'amnesia',
 'ancient',
 'ancientkorea',
 'angel',
 'ani',
 'anniversari',
 'announc',
 'anoth',
 'antholog',
 'antisoci',
 'antisocialpersonalitydisord',
 'anyth',
 'apart',
 'apocalyps',
 'apocalypticfutur',
 'app',
 'appeal',
 'appear',
 'appearance',
 'applianc',
 'appoint',
 'april',
 'archaeologist',
 'area',
 'arrog',
 'art',
 'arth',
 'arthdal',
 'artificialintellig',
 'artist',
 'arts',
 'asahi',
 'ashley',
 'asian',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assassination',
 'assembly',
 'assist',
 'assum',
 'athelet',
 'attempt',
 'attend',
 'attorney',
 'attract',
 'attraction',
 'audienc',
 'audiences',
 'author',
 'autism',
 'autist',
 'autobiograph',
 'averag',
 'avers',
 'await',
 'award',
 'awards',
 'away',
 'ba',
 'babi',
 'backdrop',
 'background',
 'bad',
 'bae',
 'baedoona',
 'baehae',
 'baehyeon',
 'baein',
 'baek',
 'baeksang',
 'baeksoo',
 'baeksung',
 'baesuzi',
 'baeyong',
 'baggag',
 'balanc',
 'band',
 'banker',
 'bankruptci',
 'bar',
 'bargain',
 'base',
 'basebal',
 'baseballplay',
 'basedoncartoon',
 'basedoncom',
 'basedonmovi',
 'basedonnovelorbook',
 'basedonshortfilm',
 'basedontruestori',
 'basedonwebcomicorwebtoon',
 'battl',
 'battlefield',
 'bawdi',
 'beach',
 'bead',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'befor',
 'begin',
 'behindthescen',
 'bekhyun',
 'belief',
 'believ',
 'belov',
 'benefit',
 'beom',
 'best',
 'bestsel',
 'bestsellingauthor',
 'betray',
 'better',
 'big',
 'biggest',
 'billion',
 'bin',
 'biographi',
 'birth',
 'bit',
 'bitter',
 'bizarr',
 'bl',
 'black',
 'blind',
 'blinddat',
 'bliss',
 'blood',
 'bloodi',
 'blunt',
 'bodi',
 'body',
 'bodyguard',
 'bok',
 'bomb',
 'bona',
 'bond',
 'bong',
 'boost',
 'born',
 'borrow',
 'boss',
 'bossam',
 'bountyhunt',
 'bowel',
 'boxer',
 'boy',
 'boyband',
 'boyfriend',
 'boys',
 'brain',
 'brainsurgeri',
 'brawn',
 'break',
 'bride',
 'bright',
 'brighter',
 'brilliant',
 'brink',
 'broadcast',
 'broke',
 'broken',
 'brokenpromis',
 'bromanc',
 'brother',
 'brotherhood',
 'brothersisterrelationship',
 'buam',
 'buddha',
 'build',
 'built',
 'bulli',
 'bulling',
 'burn',
 'busan',
 'business',
 'businessman',
 'butcher',
 'byeonwoo',
 'byul',
 'calcul',
 'came',
 'camera',
 'campus',
 'campuslif',
 'campusrom',
 'cancer',
 'captur',
 'car',
 'caraccid',
 'card',
 'care',
 'career',
 'caregiv',
 'carrefour',
 'carri',
 'case',
 'cases',
 'cash',
 'casino',
 'cassano',
 'castl',
 'catastroph',
 'caught',
 'caus',
 'center',
 'centuries',
 'ceo',
 'cha',
 'chae',
 'chaebol',
 'chaejong',
 'chaejung',
 'chain',
 'chairman',
 'chajaedol',
 'challeng',
 'chan',
 'chanc',
 'chang',
 'changryul',
 'chao',
 'chaotic',
 'charact',
 'characterdevelop',
 'charae',
 'charisma',
 'charismaticfemalelead',
 'charm',
 'chart',
 'chase',
 'chast',
 'cheat',
 'chef',
 'cheol',
 'cheom',
 'cheon',
 'chief',
 'child',
 'childabus',
 'childhood',
 'childhoodfriend',
 'childhoodtrauma',
 'children',
 'china',
 'cho',
 'choechanyi',
 'chohyuk',
 'choi',
 'choic',
 'choihang',
 'choijung',
 'choimin',
 'choimoon',
 'choisoo',
 'choiwoo',
 'choiyeo',
 'choiyoung',
 'chojae',
 'chojung',
 'chomin',
 'chonam',
 'chooja',
 'choos',
 'chooyoung',
 'chorong',
 'chosen',
 'choseong',
 'choyi',
 'chu',
 'chul',
 'chun',
 'chung',
 'chunwoo',
 'cinderella',
 'cinematography',
 'circus',
 'citi',
 'city',
 'civil',
 'clad',
 'claim',
 'class',
 'classifi',
 'classmat',
 'cliff',
 'close',
 'closer',
 'clothing',
 'clown',
 'club',
 'clumsi',
 'coexist',
 'cohabit',
 'cold',
 'collaboration',
 'collaps',
 'collapse',
 'colleagu',
 'collect',
 'colleg',
 'college',
 'collegelif',
 'coloni',
 'color',
 'coma',
 'come',
 'comeback',
 'comedi',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'commemor',
 'commiss',
 'commit',
 'common',
 'commun',
 'communication',
 'compani',
 'company',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'compromis',
 'comrades',
 'concern',
 'condemnations',
 'condition',
 'conflict',
 'confront',
 'conglomer',
 'congress',
 'connect',
 'connected',
 'conscious',
 'consecut',
 'consiglier',
 'conspiraci',
 'conspiracy',
 'conspirators',
 'constantli',
 'consult',
 'continu',
 'control',
 'controversi',
 'conveni',
 'convict',
 'cook',
 'cop',
 'core',
 'corner',
 'corp',
 'corpor',
 'corrupt',
 'cosmet',
 'cost',
 'costs',
 'couldn',
 'council',
 'countri',
 'countrysid',
 'countryside',
 'coup',
 'coupl',
 'court',
 'courtcas',
 'courtroom',
 'cover',
 'crash',
 'creat',
 'creator',
 'crew',
 'cri',
 'crime',
 'crimin',
 'critic',
 'cross',
 'crossdress',
 'cruelti',
 'cult',
 'culture',
 'curs',
 'curse',
 'custom',
 'customari',
 'cut',
 'cutthroat',
 'cyberbulli',
 'cynic',
 'da',
 'dal',
 'dam',
 'danger',
 'dark',
 'darkfairytal',
 'date',
 'datingapp',
 'daughter',
 'dawoon',
 'day',
 'days',
 'dead',
 'deal',
 'death',
 'deathmatch',
 'deathofabroth',
 'debut',
 'deceas',
 'decemb',
 'decept',
 'decid',
 'decommiss',
 'dedic',
 'deepli',
 'defam',
 'defin',
 'degener',
 'delic',
 'deliv',
 'demand',
 'democrat',
 'deok',
 'depict',
 'depress',
 'dermatologist',
 'design',
 'desir',
 'desire',
 'desires',
 'desper',
 'destroy',
 'detect',
 'detective',
 'determin',
 'develop',
 'deviat',
 'did',
 'die',
 'died',
 'differ',
 'different',
 'difficult',
 'difficulti',
 'digest',
 'dilig',
 'dinner',
 'direction',
 'director',
 'directors',
 'dirti',
 'disappear',
 'disapprovingpar',
 'disast',
 'discharg',
 'disciple',
 'disconnect',
 'discov',
 'disease',
 'disguis',
 'dismissals',
 'disord',
 'display',
 'dissoci',
 'dissociativeidentitydisord',
 'district',
 'divin',
 'divorc',
 'divorcedman',
 'dj',
 'doctor',
 'doe',
 'doesn',
 'dogs',
 'dohkyung',
 'dong',
 'dongha',
 'donguibogam',
 'doo',
 'dormitori',
 'doubleident',
 'doubt',
 'downplay',
 'drag',
 'drama',
 'dramat',
 'draw',
 'drawn',
 'dream',
 'dreams',
 'driven',
 'drug',
 'drugdeal',
 'druglord',
 'dumpi',
 'dure',
 'dwi',
 'dying',
 'dynasti',
 'dynasty',
 'earli',
 'earth',
 'earthquak',
 'easi',
 'eat',
 'eating',
 'eccentr',
 'eccentricmalelead',
 'eclect',
 'economi',
 'economy',
 'educ',
 'education',
 'effort',
 'ehwa',
 'electronics',
 'elev',
 'elit',
 'eloqu',
 'els',
 'emancip',
 'emmi',
 'emot',
 'emotion',
 'emotionalbreakdown',
 'employ',
 'employe',
 'employee',
 'employeerelationship',
 'employees',
 'employer',
 'empress',
 'encag',
 'end',
 'enemi',
 'energi',
 'engag',
 'engineer',
 'enigmat',
 'enjoy',
 'ensnar',
 'ensu',
 'ensur',
 'entangl',
 'enter',
 'entertain',
 'entertainmentindustri',
 'enthusiast',
 'entranceexamin',
 'entrepreneur',
 'envi',
 'envis',
 'eom',
 'episod',
 'episodes',
 'epitom',
 'era',
 'error',
 'escap',
 'establish',
 'eulji',
 'eum',
 'eun',
 'eunji',
 'event',
 'events',
 'eventu',
 'everi',
 'everyday',
 'everyon',
 'everyth',
 'exactli',
 'examination',
 'excel',
 'exchanged',
 'exhaust',
 'exist',
 'exorc',
 'exorcist',
 'expand',
 'expans',
 'expatri',
 'expens',
 'experi',
 'experienc',
 'explor',
 'extraordinari',
 'extrem',
 'eye',
 'face',
 'facil',
 'fact',
 'faction',
 'factions',
 'fail',
 'fairi',
 'faith',
 'fakeident',
 'fall',
 'fallen',
 'fals',
 'fame',
 'famili',
 'family',
 'familydrama',
 'familyrelationship',
 'fanci',
 'fantasi',
 'fantasyworld',
 'far',
 'fashion',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'fault',
 'featur',
 'februari',
 'fee',
 'feel',
 'fell',
 'fellow',
 'femal',
 'femalecenteredplot',
 'femalefriendship',
 'femaleprotagonist',
 'femalewrit',
 'fenc',
 'fencer',
 'festiv',
 'festival',
 'fi',
 'fianc',
 'fiancé',
 'fiancée',
 'fiction',
 'fictionalgameshow',
 'field',
 'fifth',
 'fight',
 'fighter',
 'figur',
 'figures',
 'film',
 'final',
 'financi',
 'financialcrisi',
 'fine',
 'firm',
 'firstlov',
 'fish',
 'flashback',
 'fled',
 'flirtati',
 'flower',
 'focus',
 'folk',
 'follow',
 'food',
 'footstep',
 'forc',
 'forens',
 'forese',
 'forest',
 'form',
 'formerprison',
 'forth',
 'forti',
 'fought',
 'fox',
 'france',
 'fraud',
 'free',
 'freedom',
 'friend',
 'friendli',
 'friends',
 'friendship',
 'friendstolov',
 'frighten',
 'frosti',
 'frozen',
 'fulfil',
 'funeral',
 'fusion',
 'futur',
 'future',
 'gain',
 'gam',
 'gambles',
 'game',
 'games',
 'gang',
 'gangnam',
 'gangnamscand',
 'gangs',
 'gangster',
 'gather',
 'gau',
 'gave',
 'gayrom',
 'gener',
 'general',
 'genuin',
 'geon',
 'germany',
 'geun',
 'ghost',
 'ghosthunt',
 'gi',
 'giant',
 'gift',
 'girl',
 'girlfriend',
 'giveaway',
 'given',
 'glamor',
 'glorif',
 'goah',
 'gods',
 'goe',
 'goes',
 'goguryeo',
 'gohdoo',
 'gokyung',
 'gold',
 'golden',
 'gone',
 'gonghyo',
 'gongseung',
 'gongyoo',
 'goo',
 'good',
 'gook',
 'gore',
 'goryeodynasti',
 'gotop',
 'govern',
 'governmentoffici',
 'gowoo',
 'grade',
 'gradual',
 'graduat',
 'grand',
 'grandchild',
 'great',
 'greed',
 'greenhous',
 'grew',
 'grief',
 'grim',
 'grima',
 'grimreap',
 'gritti',
 'grittyfantasi',
 'ground',
 'group',
 'grow',
 'grown',
 'gu',
 'guard',
 'guardian',
 'guest',
 'guesthous',
 'guid',
 'guidance',
 'guild',
 'guilt',
 'guk',
 'gum',
 'gumiho',
 'gun',
 'gung',
 'guy',
 'gwangha',
 'gyeo',
 'ha',
 'habyung',
 'hae',
 'hahee',
 'hair',
 'haji',
 'hajun',
 'hajung',
 'half',
 'ham',
 'han',
 'hand',
 'handa',
 'handsom',
 'handsome',
 'hangi',
 'hanhe',
 'hanhye',
 'hani',
 'hanji',
 'hanseo',
 'hanso',
 'hansuk',
 'hanyeri',
 'happen',
 'happiness',
 'hard',
 'hardship',
 'hardwork',
 'head',
 'headquart',
 'heal',
 'heart',
 'heartwarm',
 'heaven',
 'heavenlyfantasi',
 'heavi',
 'heavili',
 'hee',
 'heekim',
 'heir',
 'hell',
 'help',
 'heo',
 'heon',
 'hero',
 'heuksa',
 'heung',
 'hi',
 'hiccup',
 'hidden',
 'hiddenident',
 'hide',
 'high',
 'highfantasi',
 'highlight',
 'highschool',
 'highschoolsport',
 'hilari',
 'hire',
 'histor',
 'historical',
 'historicaldrama',
 'historicalfict',
 'history',
 'hit',
 'ho',
 'hold',
 'holland',
 'hologram',
 'home',
 'hometown',
 'honest',
 'honesty',
 'hong',
 'hongchang',
 'hongji',
 'hongjong',
 'hongseok',
 'honor',
 'hoon',
 'hope',
 'horror',
 'hospit',
 'hospital',
 'hotel',
 'hoteli',
 'hotelier',
 'hour',
 'hous',
 'house',
 'housem',
 'housemates',
 'housew',
 'housewif',
 'houston',
 'hu',
 'huge',
 'human',
 'humanlik',
 'humor',
 'hun',
 'hundr',
 'hunter',
 'hurjin',
 'husband',
 'hwa',
 ...]

In [44]:
import nltk

In [45]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [159]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [160]:
new_df['tags'][0]

'a young woman join forc with a ufo enthusiast to investig her boyfriend’ sudden disappear and stumbl into a wild conspiracy. jeonyeo-been nana leedong-hwi rohdeok drama comedi mysteri sci-fi&fantasi friendship investig ufo miniseri suspens'

In [163]:
stem('a young woman joins forces with a ufo enthusiast to investigate her boyfriend’s sudden disappearance and stumbles into a wild conspiracy. jeonyeo-been nana leedong-hwi rohdeok drama comedy mystery sci-fi&fantasy friendship investigation ufo miniseries suspense')

'a young woman join forc with a ufo enthusiast to investig her boyfriend’ sudden disappear and stumbl into a wild conspiracy. jeonyeo-been nana leedong-hwi rohdeok drama comedi mysteri sci-fi&fantasi friendship investig ufo miniseri suspens'

In [162]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp/ipykernel_9312/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
similarity = cosine_similarity(vectors)

In [139]:
similarity.shape

(131, 131)

In [167]:
similarity[new_df['name']=='Glitch']

array([[1.        , 0.13430383, 0.05647825, 0.14119562, 0.11941629,
        0.05189993, 0.13430383, 0.0492366 , 0.10874545, 0.12833175,
        0.12712835, 0.06686508, 0.09869275, 0.08827348, 0.02787473,
        0.03798686, 0.14770979, 0.12501993, 0.09847319, 0.05647825,
        0.04747572, 0.09379581, 0.04494666, 0.04494666, 0.09065192,
        0.08703883, 0.03711348, 0.09697623, 0.07312724, 0.03350126,
        0.05970814, 0.08843154, 0.16943475, 0.14213381, 0.21212121,
        0.05723638, 0.11941629, 0.06477503, 0.03191535, 0.10948978,
        0.06579517, 0.03413944, 0.14119562, 0.03260773, 0.11009638,
        0.02752409, 0.07460471, 0.05951397, 0.05732252, 0.05574947,
        0.20483662, 0.03553345, 0.05437272, 0.06030227, 0.09984038,
        0.10660036, 0.05802589, 0.02594996, 0.09534626, 0.08827348,
        0.07422696, 0.05802589, 0.05437272, 0.07242068, 0.0527535 ,
        0.04222003, 0.02901294, 0.11447276, 0.11396058, 0.02580699,
        0.08257228, 0.03350126, 0.09304842, 0.06579517, 0.07106691,
        0.07689464, 0.05078367, 0.08471737, 0.02686077, 0.07699905,
        0.17407766, 0.13834289, 0.06946455, 0.02368897, 0.09670981,
        0.11769798, 0.06579517, 0.02080626, 0.02486824, 0.03970464,
        0.0520447 , 0.04351941, 0.04511406, 0.03481553, 0.07597372,
        0.03126527, 0.01795474, 0.02963695, 0.08151933, 0.14598637,
        0.07329992, 0.17588162, 0.12833175, 0.03993615, 0.0513327 ,
        0.02326211, 0.03178209, 0.02787473, 0.10118058, 0.06154575,
        0.07041788, 0.11817161, 0.06857255, 0.03534982, 0.07106691,
        0.07963978, 0.01983799, 0.0492366 , 0.08585457, 0.03397648,
        0.17912443, 0.07834107, 0.0725954 , 0.06731489, 0.02896827,
        0.02566635, 0.07784989, 0.04494666, 0.05504819, 0.1266601 ,
        0.01785999]])

In [169]:
index = [new_df['name']=='Glitch']
similarity[index]

C:\Users\HP\AppData\Local\Temp/ipykernel_9312/2868633298.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  similarity[index]

array([[1.        , 0.13430383, 0.05647825, 0.14119562, 0.11941629,
        0.05189993, 0.13430383, 0.0492366 , 0.10874545, 0.12833175,
        0.12712835, 0.06686508, 0.09869275, 0.08827348, 0.02787473,
        0.03798686, 0.14770979, 0.12501993, 0.09847319, 0.05647825,
        0.04747572, 0.09379581, 0.04494666, 0.04494666, 0.09065192,
        0.08703883, 0.03711348, 0.09697623, 0.07312724, 0.03350126,
        0.05970814, 0.08843154, 0.16943475, 0.14213381, 0.21212121,
        0.05723638, 0.11941629, 0.06477503, 0.03191535, 0.10948978,
        0.06579517, 0.03413944, 0.14119562, 0.03260773, 0.11009638,
        0.02752409, 0.07460471, 0.05951397, 0.05732252, 0.05574947,
        0.20483662, 0.03553345, 0.05437272, 0.06030227, 0.09984038,
        0.10660036, 0.05802589, 0.02594996, 0.09534626, 0.08827348,
        0.07422696, 0.05802589, 0.05437272, 0.07242068, 0.0527535 ,
        0.04222003, 0.02901294, 0.11447276, 0.11396058, 0.02580699,
        0.08257228, 0.03350126, 0.09304842, 0.06579517, 0.07106691,
        0.07689464, 0.05078367, 0.08471737, 0.02686077, 0.07699905,
        0.17407766, 0.13834289, 0.06946455, 0.02368897, 0.09670981,
        0.11769798, 0.06579517, 0.02080626, 0.02486824, 0.03970464,
        0.0520447 , 0.04351941, 0.04511406, 0.03481553, 0.07597372,
        0.03126527, 0.01795474, 0.02963695, 0.08151933, 0.14598637,
        0.07329992, 0.17588162, 0.12833175, 0.03993615, 0.0513327 ,
        0.02326211, 0.03178209, 0.02787473, 0.10118058, 0.06154575,
        0.07041788, 0.11817161, 0.06857255, 0.03534982, 0.07106691,
        0.07963978, 0.01983799, 0.0492366 , 0.08585457, 0.03397648,
        0.17912443, 0.07834107, 0.0725954 , 0.06731489, 0.02896827,
        0.02566635, 0.07784989, 0.04494666, 0.05504819, 0.1266601 ,
        0.01785999]])

In [140]:
def recommend(kdrama):
    drama_index = new_df[new_df['name']== '49 Days'].index[0]
    distances = similarity[drama_index]
    drama_list = sorted(list(enumerate(distances)),reverse = True, key = lambda x : x[1])[1:6]
    
    for i in drama_list:
        print(new_df.iloc[i[0]]["name"])

In [142]:
#recommend('All of Us Are Dead')
#recommend('Business Proposal')
#recommend('Goblin')
new_df[new_df['name']=='49 Days']

     tmdb_id     name                                               tags
388    38861  49 Days  shin ji hyun wa enjoy absolut bliss as she wa ...

In [145]:
index = new_df[new_df['name'] == '49 Days'].index[0]
index

388

In [77]:
!pip install streamlit

Collecting streamlit

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mysql-connector-python 8.0.30 requires protobuf<=3.20.1,>=3.11.0, but you have protobuf 3.20.3 which is incompatible.

  Downloading streamlit-1.12.0-py2.py3-none-any.whl (9.1 MB)
Requirement already satisfied: toml in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (4.8.1)
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.8.0b4-py2.py3-none-any.whl (4.7 MB)
Requirement already satisfied: pandas>=0.21.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (1.3.4)
Collecting cachetools>=4.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: tornado>=5.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (6.1)
Collecting validators>=0.2
  Downloading validators-0.20.0.tar.gz (30 kB)
Requirement already satisfied: requests>=2.4 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (2.26.0)
Collecting rich>=10.11.0
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
Requirement already satisfied: watchdog in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (2.1.3)
Collecting semver
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: packaging>=14.1 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (21.0)
Collecting pyarrow>=4.0
  Downloading pyarrow-10.0.0-cp39-cp39-win_amd64.whl (20.0 MB)
Requirement already satisfied: pillow>=6.2.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (8.4.0)
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
Requirement already satisfied: click>=7.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (8.0.3)
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.29-py3-none-any.whl (182 kB)
Collecting altair>=3.2.0
  Downloading altair-4.2.0-py3-none-any.whl (812 kB)
Collecting blinker>=1.0.0
  Downloading blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting protobuf<4,>=3.12
  Downloading protobuf-3.20.3-cp39-cp39-win_amd64.whl (904 kB)
Requirement already satisfied: python-dateutil in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (2.8.2)
Collecting tzlocal>=1.1
  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (1.20.3)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\hp\anaconda3\lib\site-packages (from streamlit) (3.10.0.2)
Requirement already satisfied: jinja2 in c:\users\hp\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (2.11.3)
Requirement already satisfied: jsonschema>=3.0 in c:\users\hp\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (3.2.0)
Requirement already satisfied: toolz in c:\users\hp\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (0.11.1)
Requirement already satisfied: entrypoints in c:\users\hp\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (0.3)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from click>=7.0->streamlit) (0.4.4)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: zipp>=0.5 in c:\users\hp\anaconda3\lib\site-packages (from importlib-metadata>=1.4->streamlit) (3.6.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (21.2.0)
Requirement already satisfied: six>=1.11.0 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (1.16.0)
Requirement already satisfied: setuptools in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (58.0.4)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (0.18.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\hp\anaconda3\lib\site-packages (from packaging>=14.1->streamlit) (3.0.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.21.0->streamlit) (2021.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\hp\anaconda3\lib\site-packages (from jinja2->altair>=3.2.0->streamlit) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (1.26.7)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\hp\anaconda3\lib\site-packages (from rich>=10.11.0->streamlit) (2.10.0)
Requirement already satisfied: tzdata in c:\users\hp\anaconda3\lib\site-packages (from tzlocal>=1.1->streamlit) (2022.1)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: decorator>=3.4.0 in c:\users\hp\anaconda3\lib\site-packages (from validators>=0.2->streamlit) (5.1.0)
Building wheels for collected packages: validators
  Building wheel for validators (setup.py): started
  Building wheel for validators (setup.py): finished with status 'done'
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19583 sha256=b7e3311e469cda9d1d001043db305a62a9703e47960feb94b97d5e7487e381a8
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\2d\f0\a8\1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built validators
Installing collected packages: smmap, pytz-deprecation-shim, gitdb, commonmark, validators, tzlocal, semver, rich, pympler, pydeck, pyarrow, protobuf, gitpython, cachetools, blinker, altair, streamlit
Successfully installed altair-4.2.0 blinker-1.5 cachetools-5.2.0 commonmark-0.9.1 gitdb-4.0.9 gitpython-3.1.29 protobuf-3.20.3 pyarrow-10.0.0 pydeck-0.8.0b4 pympler-1.0.1 pytz-deprecation-shim-0.1.0.post0 rich-12.6.0 semver-2.13.0 smmap-5.0.0 streamlit-1.12.0 tzlocal-4.2 validators-0.20.0

In [147]:
images = df1.drop(['keywords','directors_ids','cast_ids','genres_ids','synopsis','tags'],axis='columns')
images

,tmdb_id,name,poster_img_url
0,136699,Glitch,https://image.tmdb.org/t/p/original/dspwDOosid...
1,99966,All of Us Are Dead,https://image.tmdb.org/t/p/original/pTEFqAjLd5...
2,93405,Squid Game,https://image.tmdb.org/t/p/original/dDlEmu3EZ0...
5,67915,Goblin,https://image.tmdb.org/t/p/original/c2gon6zbqz...
6,106651,Hellbound,https://image.tmdb.org/t/p/original/5NYdSAnDVI...
...,...,...,...
1123,118931,How to Be Thirty,https://image.tmdb.org/t/p/original/3fqu5NZEpN...
1153,199923,Ocean Likes Me,https://image.tmdb.org/t/p/original/brjI8zYGLs...
1323,78011,Amnok River Flows,https://image.tmdb.org/t/p/original/br5bVmklHe...
1330,112486,Big Bet,https://image.tmdb.org/t/p/original/b7wLXWOdey...
1374,195743,Recipe for Farewell,https://image.tmdb.org/t/p/original/2xbkLAQnNF...

In [155]:
index = images[images['name'] == '49 Days']
index

     tmdb_id     name                                     poster_img_url
388    38861  49 Days  https://image.tmdb.org/t/p/original/wBwDrV7HFK...

In [113]:
new_df.head(1)

   tmdb_id    name                                               tags
0   136699  Glitch  a young woman join forc with a ufo enthusiast ...

In [149]:
similarity.shape

(131, 131)

In [115]:
import pickle
pickle.dump(new_df,open('kdrama_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [135]:
pickle.dump(images,open('data.pkl','wb'))

In [118]:
images.head(1)

   tmdb_id    name                                     poster_img_url
0   136699  Glitch  https://image.tmdb.org/t/p/original/dspwDOosid...

In [129]:
images[images['name']=='Glitch']['poster_img_url']

0    https://image.tmdb.org/t/p/original/dspwDOosid...
Name: poster_img_url, dtype: object

In [133]:
images['title'] = images['name']
images.head(1)

   tmdb_id    name                                     poster_img_url   title
0   136699  Glitch  https://image.tmdb.org/t/p/original/dspwDOosid...  Glitch

In [134]:
images = images.drop(['name'],axis='columns')
images

,tmdb_id,poster_img_url,title
0,136699,https://image.tmdb.org/t/p/original/dspwDOosid...,Glitch
1,99966,https://image.tmdb.org/t/p/original/pTEFqAjLd5...,All of Us Are Dead
2,93405,https://image.tmdb.org/t/p/original/dDlEmu3EZ0...,Squid Game
5,67915,https://image.tmdb.org/t/p/original/c2gon6zbqz...,Goblin
6,106651,https://image.tmdb.org/t/p/original/5NYdSAnDVI...,Hellbound
...,...,...,...
1123,118931,https://image.tmdb.org/t/p/original/3fqu5NZEpN...,How to Be Thirty
1153,199923,https://image.tmdb.org/t/p/original/brjI8zYGLs...,Ocean Likes Me
1323,78011,https://image.tmdb.org/t/p/original/br5bVmklHe...,Amnok River Flows
1330,112486,https://image.tmdb.org/t/p/original/b7wLXWOdey...,Big Bet
1374,195743,https://image.tmdb.org/t/p/original/2xbkLAQnNF...,Recipe for Farewell

In [136]:
pickle.dump(images,open('data_drama.pkl','wb'))